version: "3.7"

services:
  web-app:
    build:
      context: ./
#    container_name: web-app
#    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./service:/web-app/service
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres-volume:/var/lib/postgresql/data/

volumes:
  postgres-volume: