version: "3.7"

services:
  web-app:
    build:
      context: ./
#    container_name: web-app
#    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./service:/web-app/service
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"